export const JOIN = 100,
    READY = 101,
    JOIN_FAILED = 0,
    JOIN_SUCCEEDED = 1,
    ROOM_DOES_NOT_EXIST = 0,
    INCORRECT_PASSWORD = 1,
    NAME_INVALID = 200,
    NAME_SET_SUCCESSFULLY = 201;
